name: Sync secrets to AWS SSM

on:
  workflow_dispatch: # manual trigger only

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  sync-ssm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::170037050003:role/github-ssm-role
          aws-region: ap-southeast-1

      - name: Create / Update SSM parameters
        run: |
          aws ssm put-parameter \
            --name "/joblyai/prod/RAPID_API_KEY" \
            --value "${{ secrets.RAPID_API_KEY }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/RAPID_API_HOST" \
            --value "${{ secrets.RAPID_API_HOST }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/OPENAI_MODEL" \
            --value "${{ secrets.OPENAI_MODEL }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/OPENAI_API_KEY" \
            --value "${{ secrets.OPENAI_API_KEY }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/DATABASE_URL" \
            --value "${{ secrets.DATABASE_URL }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/REDIS_URL" \
            --value "${{ secrets.REDIS_URL }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/SUPABASE_JWT_SECRET" \
            --value "${{ secrets.SUPABASE_JWT_SECRET }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/AWS_REGION" \
            --value "${{ secrets.AWS_REGION }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/AWS_S3_BUCKET_NAME" \
            --value "${{ secrets.AWS_S3_BUCKET_NAME }}" \
            --type SecureString \
            --overwrite
            
          aws ssm put-parameter \
            --name "/joblyai/prod/IMAGE_KIT_PUBLIC_KEY" \
            --value "${{ secrets.IMAGE_KIT_PUBLIC_KEY }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/IMAGE_KIT_PRIVATE_KEY" \
            --value "${{ secrets.IMAGE_KIT_PRIVATE_KEY }}" \
            --type SecureString \
            --overwrite

          aws ssm put-parameter \
            --name "/joblyai/prod/IMAGE_KIT_URL_ENDPOINT" \
            --value "${{ secrets.IMAGE_KIT_URL_ENDPOINT }}" \
            --type SecureString \
            --overwrite
